#!/usr/bin/env node

const fs = require('node:fs');
const path = require('node:path');
const yaml = require('js-yaml');

/**
 * Advanced Test Report Generator for Maestro E2E Tests
 * Generates comprehensive HTML and JSON reports similar to Istanbul/Jest
 */
class TestReportGenerator {
  constructor() {
    this.testResults = {
      timestamp: new Date().toISOString(),
      totalSuites: 0,
      totalTests: 0,
      passedTests: 0,
      failedTests: 0,
      skippedTests: 0,
      pendingTests: 0,
      executionTime: 0,
      suites: [],
      summary: {
        status: 'unknown',
        coverage: {
          passRate: 0,
          failRate: 0,
          skipRate: 0,
          pendingRate: 0
        }
      }
    };
    this.executedTests = new Set();
  }

  /**
   * Load test metadata generated by SDK methods during test generation
   */
  loadTestMetadata(metadataPath) {
    try {
      if (!fs.existsSync(metadataPath)) {
        console.warn('Test metadata file not found, falling back to parsing master suite');
        return null;
      }

      const metadataContent = fs.readFileSync(metadataPath, 'utf8');
      const metadata = JSON.parse(metadataContent);
      
      // Convert SDK metadata to report format
      const suites = metadata.suites.map(suite => ({
        id: suite.id,
        name: suite.name,
        screenName: suite.screenName,
        file: suite.fileName,
        testCount: suite.testCount,
        tests: suite.tests.map(test => ({
          id: test.id,
          title: test.title,
          description: test.description,
          type: test.type,
          status: 'pending',
          executionTime: 0,
          steps: test.steps,
          preconditions: test.preconditions,
          error: null,
          optional: false
        })),
        status: 'pending',
        executionTime: 0,
        errors: []
      }));

      return {
        metadata: metadata,
        suites: suites
      };
    } catch (error) {
      console.error('Error loading test metadata:', error.message);
      return null;
    }
  }

  /**
   * Create a new suite object from a suite name
   */
  createSuiteEntry(suiteName) {
    return {
      name: suiteName,
      file: '',
      testCount: 0,
      tests: [],
      status: 'pending',
      executionTime: 0,
      errors: []
    };
  }

  /**
   * Process a single line from the master suite file; returns updated currentSuite
   */
  processMasterSuiteLine(trimmedLine, currentSuite, suites) {
    if (trimmedLine.startsWith('# Suite:')) {
      if (currentSuite) {
        suites.push(currentSuite);
      }
      return this.createSuiteEntry(trimmedLine.replace('# Suite:', '').trim());
    }
    if (trimmedLine.startsWith('# Consolidated flow file:') && currentSuite) {
      currentSuite.file = trimmedLine.replace('# Consolidated flow file:', '').trim();
    } else if (trimmedLine.startsWith('# Contains') && trimmedLine.includes('test case(s):') && currentSuite) {
      const tcIdx = trimmedLine.indexOf(' test case');
      if (tcIdx > 0) {
        const before = trimmedLine.substring(0, tcIdx);
        const lastSpace = before.lastIndexOf(' ');
        const numStr = before.substring(lastSpace + 1);
        const parsed = Number.parseInt(numStr, 10);
        if (!Number.isNaN(parsed)) {
          currentSuite.testCount = parsed;
        }
      }
    }
    return currentSuite;
  }

  /**
   * Parse master suite YAML to extract test suite structure (fallback method)
   */
  parseMasterSuite(masterSuitePath) {
    try {
      const masterContent = fs.readFileSync(masterSuitePath, 'utf8');
      const lines = masterContent.split('\n');

      const suites = [];
      let currentSuite = null;

      for (const line of lines) {
        currentSuite = this.processMasterSuiteLine(line.trim(), currentSuite, suites);
      }

      if (currentSuite) {
        suites.push(currentSuite);
      }

      return suites;
    } catch (error) {
      console.error('Error parsing master suite:', error.message);
      return [];
    }
  }

  /**
   * Create a test object from a parsed comment line
   */
  createTestFromLine(trimmedLine, suiteName, testIndex) {
    const dotIdx = trimmedLine.indexOf('.');
    if (dotIdx <= 0) return null;
    const colonIdx = trimmedLine.indexOf(':', dotIdx);
    if (colonIdx <= dotIdx) return null;
    return {
      id: `${suiteName}_test_${testIndex}`,
      title: trimmedLine.substring(dotIdx + 1, colonIdx).trim(),
      description: trimmedLine.substring(colonIdx + 1).trim(),
      status: 'pending',
      executionTime: 0,
      steps: [],
      error: null,
      optional: false
    };
  }

  /**
   * Parse individual suite YAML files to extract test cases
   */
  parseSuiteFile(suitePath, suiteName) {
    try {
      if (!fs.existsSync(suitePath)) {
        return [];
      }

      const suiteContent = fs.readFileSync(suitePath, 'utf8');
      const lines = suiteContent.split('\n');

      const tests = [];
      let currentTest = null;
      let testIndex = 0;

      for (const line of lines) {
        const trimmedLine = line.trim();

        if (trimmedLine.match(/^#\s*\d+\.\s*/)) {
          if (currentTest) {
            tests.push(currentTest);
          }
          testIndex++;
          currentTest = this.createTestFromLine(trimmedLine, suiteName, testIndex);
        }

        if (trimmedLine.startsWith('- runFlow:') && currentTest) {
          currentTest.steps.push({
            type: 'runFlow',
            description: 'Execute reusable flow',
            status: 'pending'
          });
        }
      }

      if (currentTest) {
        tests.push(currentTest);
      }

      return tests;
    } catch (error) {
      console.error(`Error parsing suite file ${suitePath}:`, error.message);
      return [];
    }
  }

  /**
   * Check if a log line contains an error indicator
   */
  isErrorLine(line) {
    const errorPatterns = [
      'FAILED', 'ERROR', 'Command exited with code 1', 'Error:',
      'Assertion is false', 'failed. Check the UI hierarchy',
      'Element not found', 'not found. Check the UI hierarchy',
      'ReferenceError:', 'SyntaxError:'
    ];
    return errorPatterns.some(p => line.includes(p));
  }

  /**
   * Check if a log line is a primary error indicator (not a secondary detail)
   */
  isPrimaryErrorLine(line) {
    const primaryPatterns = [
      'Assertion is false', 'Element not found',
      'FAILED', 'ERROR', 'ReferenceError:', 'SyntaxError:'
    ];
    return primaryPatterns.some(p => line.includes(p));
  }

  /**
   * Process a failure line: update counts, correct attributions, mark tests
   */
  processFailureLine(trimmedLine, currentMainSuite, currentFlow, failedFlows, countedErrors) {
    const elementIdMatch = trimmedLine.match(/id:\s*([^\s]+)/);
    const elementContext = elementIdMatch ? elementIdMatch[1] : trimmedLine;

    if (!this.isPrimaryErrorLine(trimmedLine) || countedErrors.has(elementContext)) return false;

    countedErrors.add(elementContext);
    if (trimmedLine.includes('FAILED') && elementIdMatch) {
      countedErrors.add(`Assertion is false: id: ${elementIdMatch[1]} is visible`);
    }

    this.testResults.failedTests++;
    const failureTarget = currentMainSuite || currentFlow;
    if (failureTarget) {
      failedFlows.add(failureTarget);
      this.addTestError(failureTarget, trimmedLine);

      const visibleMatch = trimmedLine.match(/id:\s*([^\s]+)\s+is visible/);
      if (visibleMatch) {
        const failingElementId = visibleMatch[1];
        const correctedCount = this.correctPassedTestsForFailedElement(failingElementId, trimmedLine);
        this.correctWronglyAttributedFailures(failingElementId);
        if (correctedCount === 0) {
          this.markNextTestAsFailed(failureTarget, trimmedLine);
        }
      } else {
        this.markNextTestAsFailed(failureTarget, trimmedLine);
      }
    }
    return true;
  }

  /**
   * Track flow/yaml execution from a log line; mutates ctx.currentFlow and ctx.currentMainSuite
   */
  trackFlowExecution(trimmedLine, ctx) {
    if (trimmedLine.startsWith('> Flow')) {
      const flowName = trimmedLine.split('> Flow')[1].trim();
      ctx.currentFlow = flowName;
      this.executedTests.add(flowName);
      return;
    }
    if (trimmedLine.startsWith('Run ') && trimmedLine.endsWith('.yaml...')) {
      const yamlFile = trimmedLine.replace('Run ', '').replace('...', '');
      ctx.currentFlow = yamlFile;
      if (!yamlFile.startsWith('common/')) {
        ctx.currentMainSuite = yamlFile;
      }
      this.executedTests.add(yamlFile);
    }
  }

  /**
   * Process step-level actions (COMPLETED, RUNNING, emoji indicators, errors, timing)
   */
  processLogLineActions(trimmedLine, ctx) {
    if (trimmedLine.includes('Running on') && !ctx.executionStartTime) {
      ctx.executionStartTime = Date.now();
    }
    if (trimmedLine.includes('COMPLETED') && ctx.currentMainSuite && !ctx.hasEncounteredFailure) {
      this.testResults.passedTests++;
      ctx.completedFlows.add(ctx.currentMainSuite);
      this.markNextTestAsPassed(ctx.currentMainSuite);
    }
    if (trimmedLine.includes('RUNNING') && ctx.currentFlow) {
      this.executedTests.add(ctx.currentFlow);
    }
    if (ctx.currentFlow) {
      if (trimmedLine.includes('✅')) {
        ctx.completedFlows.add(ctx.currentFlow);
      } else if (trimmedLine.includes('❌')) {
        ctx.failedFlows.add(ctx.currentFlow);
        this.addTestError(ctx.currentFlow, trimmedLine);
      }
    }
    if (this.isErrorLine(trimmedLine)) {
      if (this.processFailureLine(trimmedLine, ctx.currentMainSuite, ctx.currentFlow, ctx.failedFlows, ctx.countedErrors)) {
        ctx.hasEncounteredFailure = true;
      }
    }
    if (trimmedLine.includes('Command exited') && ctx.executionStartTime) {
      this.testResults.executionTime = Date.now() - ctx.executionStartTime;
    }
  }

  /**
   * Update suite statuses after log parsing based on completed/failed sets
   */
  updateSuiteStatusesAfterParsing(completedFlows, failedFlows) {
    for (const suite of this.testResults.suites) {
      if (!this.executedTests.has(suite.file)) continue;
      if (failedFlows.has(suite.file)) {
        suite.status = 'failed';
      } else if (completedFlows.has(suite.file)) {
        suite.status = 'passed';
      } else {
        suite.status = 'pending';
      }
    }
  }

  /**
   * Parse Maestro execution log to extract test results
   */
  parseMaestroLog(logPath) {
    try {
      if (!fs.existsSync(logPath)) {
        console.warn('Maestro log file not found, marking all tests as pending');
        return;
      }

      const logContent = fs.readFileSync(logPath, 'utf8');
      const lines = logContent.split('\n');

      // Reset counts to avoid double counting from multiple sources
      this.testResults.passedTests = 0;
      this.testResults.failedTests = 0;
      this.testResults.skippedTests = 0;
      this.logProcessed = true;

      const ctx = {
        currentFlow: null,
        currentMainSuite: null,
        executionStartTime: null,
        completedFlows: new Set(),
        failedFlows: new Set(),
        countedErrors: new Set(),
        hasEncounteredFailure: false
      };

      for (const line of lines) {
        const trimmedLine = line.trim();
        this.trackFlowExecution(trimmedLine, ctx);
        this.processLogLineActions(trimmedLine, ctx);
      }

      this.updateSuiteStatusesAfterParsing(ctx.completedFlows, ctx.failedFlows);

      // If we encountered a failure, mark all remaining tests as pending (not executed)
      if (ctx.hasEncounteredFailure) {
        this.markRemainingTestsAsPending();
        // Recalculate statistics after corrections
        this.recalculateTestStatistics();
      }

    } catch (error) {
      console.error('Error parsing Maestro log:', error.message);
    }
  }

  /**
   * Update test status based on execution results
   */
  updateTestStatus(flowName, status) {
    for (const suite of this.testResults.suites) {
      if (suite.file === flowName || suite.name.toLowerCase().includes(flowName.toLowerCase())) {
        suite.status = status;
        for (const test of suite.tests) {
          if (test.status === 'pending') {
            test.status = status;
          }
        }
        break;
      }
    }
  }

  /**
   * Mark the next pending test in a suite as passed
   */
  markNextTestAsPassed(suiteName) {
    for (const suite of this.testResults.suites) {
      if (suite.file === suiteName || suite.name.toLowerCase().includes(suiteName.toLowerCase())) {
        // Find the first pending test and mark it as passed
        for (const test of suite.tests) {
          if (test.status === 'pending') {
            test.status = 'passed';
            break; // Only mark one test at a time
          }
        }
        break;
      }
    }
  }

  /**
   * Check if a pending test matches the failing element ID
   */
  testMatchesElement(test, elementId) {
    return test.status === 'pending' && (
      test.title.includes(elementId) ||
      test.description.includes(elementId) ||
      (test.steps?.some(step => step.element === elementId))
    );
  }

  /**
   * Mark the first pending test in a suite as failed, preferring element-ID match
   */
  markFailedTestInSuite(suite, failingElementId, errorMessage) {
    if (failingElementId) {
      for (const test of suite.tests) {
        if (this.testMatchesElement(test, failingElementId)) {
          test.status = 'failed';
          test.error = errorMessage;
          return;
        }
      }
    }
    // Fallback: mark the first pending test
    for (const test of suite.tests) {
      if (test.status === 'pending') {
        test.status = 'failed';
        test.error = errorMessage;
        break;
      }
    }
  }

  /**
   * Mark the next pending test in a suite as failed
   */
  markNextTestAsFailed(suiteName, errorMessage) {
    // Extract element ID from error message if available
    const errorElementIdMatch = errorMessage.match(/id:\s*([^\s]+)\s+is visible/);
    const failingElementId = errorElementIdMatch ? errorElementIdMatch[1] : null;

    for (const suite of this.testResults.suites) {
      if (suite.file === suiteName || suite.name.toLowerCase().includes(suiteName.toLowerCase())) {
        this.markFailedTestInSuite(suite, failingElementId, errorMessage);
        break;
      }
    }
  }

  /**
   * Add error information to test
   */
  addTestError(flowName, errorMessage) {
    for (const suite of this.testResults.suites) {
      if (suite.file === flowName || suite.name.toLowerCase().includes(flowName.toLowerCase())) {
        suite.errors.push(errorMessage);
        for (const test of suite.tests) {
          if (test.status === 'failed') {
            test.error = errorMessage;
          }
        }
        break;
      }
    }
  }

  /**
   * Mark all remaining tests in all suites as pending (not executed) after failure
   */
  markRemainingTestsAsPending() {
    let foundFirstFailure = false;
    let correctedCount = 0;
    
    for (const suite of this.testResults.suites) {
      for (const test of suite.tests) {
        // Once we find the first failed test, mark all subsequent tests as pending
        if (test.status === 'failed' && !foundFirstFailure) {
          foundFirstFailure = true;
          continue; // Keep the failed test as failed
        }
        
        if (foundFirstFailure && test.status === 'passed') {
          test.status = 'pending';
          delete test.error; // Remove any error messages
          correctedCount++;
        }
      }
    }
    
    if (correctedCount > 0) {
      console.log(`✅ Corrected ${correctedCount} tests from PASSED to PENDING (not executed after failure)`);
    }
  }

  /**
   * Recalculate test statistics after corrections
   */
  recalculateTestStatistics() {
    let passedCount = 0;
    let failedCount = 0;
    let pendingCount = 0;
    
    for (const suite of this.testResults.suites) {
      for (const test of suite.tests) {
        switch (test.status) {
          case 'passed':
            passedCount++;
            break;
          case 'failed':
            failedCount++;
            break;
          case 'pending':
            pendingCount++;
            break;
        }
      }
    }
    
    this.testResults.passedTests = passedCount;
    this.testResults.failedTests = failedCount;
    this.testResults.pendingTests = pendingCount;
    this.testResults.totalTests = passedCount + failedCount + pendingCount;
  }

  /**
   * Correct already-passed tests for a specific element when a failure is detected
   */
  correctPassedTestsForFailedElement(elementId, errorMessage) {
    let correctedCount = 0;
    for (const suite of this.testResults.suites) {
      for (const test of suite.tests) {
        if (test.status === 'passed' && 
            (test.title.includes(elementId) || 
             test.description.includes(elementId))) {
          test.status = 'failed';
          test.error = errorMessage;
          correctedCount++;
        }
      }
    }
    return correctedCount;
  }

  /**
   * Correct wrongly attributed failures - remove error messages from tests that don't match the failing element
   */
  correctWronglyAttributedFailures(actualFailingElementId) {
    let correctedCount = 0;
    for (const suite of this.testResults.suites) {
      for (const test of suite.tests) {
        if (test.status === 'failed' &&
            test.error?.includes(`id: ${actualFailingElementId}`) &&
            !(test.title.includes(actualFailingElementId) || test.description.includes(actualFailingElementId))) {
          // This test has an error message for a different element - mark as pending instead
          test.status = 'pending';
          delete test.error;
          correctedCount++;
        }
      }
    }
    return correctedCount;
  }

  /**
   * Calculate test statistics
   */
  countTestsByStatus() {
    const counts = { passed: 0, failed: 0, skipped: 0, pending: 0, total: 0 };
    for (const suite of this.testResults.suites) {
      counts.total += suite.tests.length;
      for (const test of suite.tests) {
        counts[test.status] = (counts[test.status] || 0) + 1;
      }
    }
    return counts;
  }

  calculateCoverageRates(total) {
    if (total <= 0) return;
    const r = this.testResults;
    const cov = r.summary.coverage;
    cov.passRate = ((r.passedTests / total) * 100).toFixed(2);
    cov.failRate = ((r.failedTests / total) * 100).toFixed(2);
    cov.skipRate = ((r.skippedTests / total) * 100).toFixed(2);
    cov.pendingRate = ((r.pendingTests / total) * 100).toFixed(2);
  }

  calculateStatistics() {
    this.testResults.totalSuites = this.testResults.suites.length;

    if (this.logProcessed) {
      let total = 0;
      for (const suite of this.testResults.suites) { total += suite.tests.length; }
      this.testResults.totalTests = total;
      this.testResults.pendingTests = total - this.testResults.passedTests - this.testResults.failedTests - this.testResults.skippedTests;
    } else {
      const counts = this.countTestsByStatus();
      this.testResults.totalTests = counts.total;
      this.testResults.passedTests = counts.passed;
      this.testResults.failedTests = counts.failed;
      this.testResults.skippedTests = counts.skipped;
      this.testResults.pendingTests = counts.pending;
    }

    this.calculateCoverageRates(this.testResults.totalTests);

    const r = this.testResults;
    if (r.failedTests > 0) {
      r.summary.status = 'failed';
    } else if (r.passedTests > 0) {
      r.summary.status = 'passed';
    } else {
      r.summary.status = 'pending';
    }
  }

  /**
   * Generate comprehensive HTML report
   */
  generateHTMLReport() {
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Maestro E2E Test Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background: #f5f7fa; color: #333; }
        .container { max-width: 1200px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; border-radius: 10px; margin-bottom: 30px; box-shadow: 0 4px 15px rgba(0,0,0,0.1); }
        .header h1 { font-size: 2.5em; margin-bottom: 10px; }
        .header .subtitle { opacity: 0.9; font-size: 1.1em; }
        .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 20px; margin-bottom: 30px; }
        .stat-card { background: white; padding: 25px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); border-left: 5px solid #667eea; }
        .stat-card.passed { border-left-color: #28a745; }
        .stat-card.failed { border-left-color: #dc3545; }
        .stat-card.pending { border-left-color: #ffc107; }
        .stat-card.skipped { border-left-color: #6c757d; }
        .stat-number { font-size: 2.5em; font-weight: bold; margin-bottom: 5px; }
        .stat-label { color: #666; font-size: 0.9em; text-transform: uppercase; letter-spacing: 1px; }
        .progress-bar { width: 100%; height: 8px; background: #e9ecef; border-radius: 4px; overflow: hidden; margin: 10px 0; }
        .progress-fill { height: 100%; transition: width 0.3s ease; }
        .progress-fill.passed { background: #28a745; }
        .progress-fill.failed { background: #dc3545; }
        .progress-fill.pending { background: #ffc107; }
        .progress-fill.skipped { background: #6c757d; }
        .suite-card { background: white; margin-bottom: 25px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); overflow: hidden; }
        .suite-header { padding: 20px; background: #f8f9fa; border-bottom: 1px solid #dee2e6; cursor: pointer; transition: background 0.2s; }
        .suite-header:hover { background: #e9ecef; }
        .suite-header.failed { background: #f8d7da; }
        .suite-header.passed { background: #d4edda; }
        .suite-header.pending { background: #fff3cd; }
        .suite-title { font-size: 1.3em; font-weight: 600; margin-bottom: 8px; }
        .suite-meta { display: flex; justify-content: space-between; align-items: center; font-size: 0.9em; color: #666; }
        .suite-tests { padding: 0; max-height: 0; overflow: hidden; transition: max-height 0.3s ease; }
        .suite-tests.expanded { max-height: 50000px; }
        .test-item { padding: 15px 20px; border-bottom: 1px solid #f0f0f0; display: flex; justify-content: space-between; align-items: center; }
        .test-item:last-child { border-bottom: none; }
        .test-info { flex: 1; }
        .test-title { font-weight: 500; margin-bottom: 5px; }
        .test-description { color: #666; font-size: 0.9em; }
        .test-error { color: #dc3545; font-size: 0.85em; margin-top: 5px; font-family: monospace; background: #f8f8f8; padding: 8px; border-radius: 4px; }
        .status-badge { padding: 4px 12px; border-radius: 20px; font-size: 0.8em; font-weight: 600; text-transform: uppercase; }
        .status-badge.passed { background: #d4edda; color: #155724; }
        .status-badge.failed { background: #f8d7da; color: #721c24; }
        .status-badge.pending { background: #fff3cd; color: #856404; }
        .status-badge.skipped { background: #e2e3e5; color: #383d41; }
        .toggle-icon { margin-left: 10px; transition: transform 0.3s ease; }
        .toggle-icon.rotated { transform: rotate(180deg); }
        .summary-section { background: white; padding: 25px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin-bottom: 30px; }
        .summary-title { font-size: 1.5em; margin-bottom: 20px; color: #333; }
        .execution-info { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; }
        .info-item { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #f0f0f0; }
        .info-label { font-weight: 500; color: #666; }
        .info-value { font-weight: 600; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🧪 Maestro E2E Test Report</h1>
            <div class="subtitle">Generated on ${new Date(this.testResults.timestamp).toLocaleString()}</div>
        </div>

        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-number">${this.testResults.totalSuites}</div>
                <div class="stat-label">Test Suites</div>
            </div>
            <div class="stat-card">
                <div class="stat-number">${this.testResults.totalTests}</div>
                <div class="stat-label">Total Tests</div>
            </div>
            <div class="stat-card passed">
                <div class="stat-number">${this.testResults.passedTests}</div>
                <div class="stat-label">Passed</div>
                <div class="progress-bar">
                    <div class="progress-fill passed" style="width: ${this.testResults.summary.coverage.passRate}%"></div>
                </div>
            </div>
            <div class="stat-card failed">
                <div class="stat-number">${this.testResults.failedTests}</div>
                <div class="stat-label">Failed</div>
                <div class="progress-bar">
                    <div class="progress-fill failed" style="width: ${this.testResults.summary.coverage.failRate}%"></div>
                </div>
            </div>
            <div class="stat-card pending">
                <div class="stat-number">${this.testResults.pendingTests}</div>
                <div class="stat-label">Pending</div>
                <div class="progress-bar">
                    <div class="progress-fill pending" style="width: ${this.testResults.summary.coverage.pendingRate}%"></div>
                </div>
            </div>
            <div class="stat-card skipped">
                <div class="stat-number">${this.testResults.skippedTests}</div>
                <div class="stat-label">Skipped</div>
                <div class="progress-bar">
                    <div class="progress-fill skipped" style="width: ${this.testResults.summary.coverage.skipRate}%"></div>
                </div>
            </div>
        </div>

        <div class="summary-section">
            <h2 class="summary-title">📊 Execution Summary</h2>
            <div class="execution-info">
                <div class="info-item">
                    <span class="info-label">Overall Status:</span>
                    <span class="info-value status-badge ${this.testResults.summary.status}">${this.testResults.summary.status.toUpperCase()}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Execution Time:</span>
                    <span class="info-value">${this.formatDuration(this.testResults.executionTime)}</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Pass Rate:</span>
                    <span class="info-value">${this.testResults.summary.coverage.passRate}%</span>
                </div>
                <div class="info-item">
                    <span class="info-label">Fail Rate:</span>
                    <span class="info-value">${this.testResults.summary.coverage.failRate}%</span>
                </div>
            </div>
        </div>

        <div class="suites-section">
            ${this.testResults.suites.map(suite => this.generateSuiteHTML(suite)).join('')}
        </div>
    </div>

    <script>
        function toggleSuite(element) {
            const testsContainer = element.nextElementSibling;
            const toggleIcon = element.querySelector('.toggle-icon');
            
            testsContainer.classList.toggle('expanded');
            toggleIcon.classList.toggle('rotated');
        }
    </script>
</body>
</html>`;
  }

  /**
   * Generate HTML for individual test suite
   */
  generateSuiteHTML(suite) {
    return `
        <div class="suite-card">
            <div class="suite-header ${suite.status}" onclick="toggleSuite(this)">
                <div class="suite-title">${suite.name}</div>
                <div class="suite-meta">
                    <span>📁 ${suite.file} • 🧪 ${suite.tests.length} test(s)</span>
                    <div>
                        <span class="status-badge ${suite.status}">${suite.status.toUpperCase()}</span>
                        <span class="toggle-icon">▼</span>
                    </div>
                </div>
            </div>
            <div class="suite-tests">
                ${suite.tests.map(test => `
                    <div class="test-item">
                        <div class="test-info">
                            <div class="test-title">${test.title}</div>
                            <div class="test-description">${test.description}</div>
                            ${test.error ? `<div class="test-error">❌ ${test.error}</div>` : ''}
                        </div>
                        <span class="status-badge ${test.status}">${test.status.toUpperCase()}</span>
                    </div>
                `).join('')}
            </div>
        </div>
    `;
  }

  /**
   * Format duration in human-readable format
   */
  formatDuration(ms) {
    if (ms < 1000) return `${ms}ms`;
    const seconds = Math.floor(ms / 1000);
    const minutes = Math.floor(seconds / 60);
    if (minutes > 0) {
      return `${minutes}m ${seconds % 60}s`;
    }
    return `${seconds}s`;
  }

  /**
   * Generate the complete test report
   */
  async generate(options = {}) {
    const {
      masterSuitePath = './e2e/master_suite.yaml',
      suiteDirectory = './e2e',
      logPath = './maestro-detailed-output.log',
      outputDir = './test-reports',
      metadataPath = './test-metadata.json'
    } = options;

    console.log('🚀 Generating comprehensive test report...');

    // Try to load test metadata first (preferred method using SDK data)
    const metadataResult = this.loadTestMetadata(metadataPath);
    
    if (metadataResult) {
      console.log('✅ Using SDK-generated test metadata for enhanced reporting');
      this.testResults.suites = metadataResult.suites;
      this.testResults.appName = metadataResult.metadata.appName;
      this.testResults.generated = metadataResult.metadata.generated;
    } else {
      console.log('⚠️ Falling back to YAML parsing for test structure');
      // Fallback to parsing YAML files
      const suites = this.parseMasterSuite(masterSuitePath);
      
      for (const suite of suites) {
        const suitePath = path.join(suiteDirectory, suite.file);
        suite.tests = this.parseSuiteFile(suitePath, suite.name);
      }
      
      this.testResults.suites = suites;
    }

    // Parse execution results
    this.parseMaestroLog(logPath);

    // Calculate statistics
    this.calculateStatistics();

    // Ensure output directory exists
    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    // Generate reports
    const htmlReport = this.generateHTMLReport();
    const jsonReport = JSON.stringify(this.testResults, null, 2);

    // Write reports
    fs.writeFileSync(path.join(outputDir, 'test-report.html'), htmlReport);
    fs.writeFileSync(path.join(outputDir, 'test-report.json'), jsonReport);

    console.log(`📊 Reports generated successfully!`);
    console.log(`📄 HTML Report: ${path.join(outputDir, 'test-report.html')}`);
    console.log(`📋 JSON Report: ${path.join(outputDir, 'test-report.json')}`);
    console.log(`📈 Summary: ${this.testResults.passedTests} passed, ${this.testResults.failedTests} failed, ${this.testResults.pendingTests} pending`);

    return {
      htmlPath: path.join(outputDir, 'test-report.html'),
      jsonPath: path.join(outputDir, 'test-report.json'),
      summary: this.testResults.summary
    };
  }
}

// CLI execution
if (require.main === module) {
  const generator = new TestReportGenerator();
  
  const options = {
    masterSuitePath: process.argv[2] || './e2e/master_suite.yaml',
    suiteDirectory: process.argv[3] || './e2e',
    logPath: process.argv[4] || './maestro-detailed-output.log',
    outputDir: process.argv[5] || './test-reports',
    metadataPath: process.argv[6] || './test-metadata.json'
  };

  generator.generate(options)
    .then(result => {
      console.log('✅ Test report generation completed successfully!');
      process.exit(0);
    })
    .catch(error => {
      console.error('❌ Error generating test report:', error.message);
      process.exit(1);
    });
}

module.exports = TestReportGenerator;