import React from 'react';
import { StyleProp } from 'react-native';
import { color, component, text } from '@/assets';
import { sharedStyles } from '@/components/shared/sharedStyles';
import { ASAppBar } from '@/components';

type Props = React.ComponentProps<typeof ASAppBar> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASAppBar.
 *
 * Applies the structural props that are constant across every ASAppBar
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASAppBar directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppAppBar: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASAppBar
    leadingIconSize={20}
    backIconColor={color.brand.primary}
    backIconSize={component.icon.size.lg}
    leadingShow={true}
    centerAlignment={'left'}
    leadingMode={'auto'}
    trailingShow={true}
    centerMode={'auto'}
    bottomShape={'flat'}
    variant={'default'}
    backgroundImageResizeMode={'cover'}
    actionsLayout={'row'}
    centerShow={true}
    textStyles={[
      text.title.medium,
      sharedStyles.ampAppBarAppBarAsappHeaderAppBarTextStyles,
    ]}
    subtitleStyle={[
      text.body.medium,
      sharedStyles.ampAppBarAppBarAsappHeaderAppBarSubtitle,
    ]}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppAppBar;
