import React from 'react';
import { StyleProp } from 'react-native';
import { ASContainer } from '@/components';

type Props = React.ComponentProps<typeof ASContainer> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASContainer.
 *
 * Applies the structural props that are constant across every ASContainer
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASContainer directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppContainer: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASContainer
    disabledSafeArea={false}
    isScrollable={true}
    backgroundImageResizeMode={'contain'}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppContainer;
