import React from 'react';
import { StyleProp } from 'react-native';
import { color, text } from '@/assets';
import { sharedStyles } from '@/components/shared/sharedStyles';
import { ASDropDown } from '@/components';

type Props = React.ComponentProps<typeof ASDropDown> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASDropDown.
 *
 * Applies the structural props that are constant across every ASDropDown
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASDropDown directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppDropDown: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASDropDown
    borderErrorColor={color.status.danger}
    borderActiveColor={color.brand.primary}
    isMultiChoices={false}
    search={false}
    containerStyle={
      sharedStyles.reviewAndConfirmDetailsContainerDropdownFieldAsdrDropDo2Container
    }
    labelTextStyle={[
      text.label.medium,
      sharedStyles.loginScreenInputUserNameInput2LabelText,
    ]}
    dropdownTextStyles={[
      text.body.medium,
      sharedStyles.homeInputActivateYourVirtualCardNowInputPrefixText,
    ]}
    placeholderTextStyles={[
      text.body.medium,
      sharedStyles.reviewAndConfirmDetailsContainerDropdownFieldAsdrDropDo2PlaceholderTextStyles,
    ]}
    iconStyles={
      sharedStyles.reviewAndConfirmDetailsContainerDropdownFieldAsdrDropDo2IconStyles
    }
    selectedTextStyle={[
      text.body.medium,
      sharedStyles.reviewAndConfirmDetailsContainerDropdownFieldAsdrDropDo2SelectedText,
    ]}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppDropDown;
