import React from 'react';
import { StyleProp } from 'react-native';
import { ASForm } from '@/components';

type Props = React.ComponentProps<typeof ASForm> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASForm.
 *
 * Applies the structural props that are constant across every ASForm
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASForm directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppForm: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASForm
    enableReinitialize={true}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppForm;
