import React from 'react';
import { StyleProp } from 'react-native';
import { sharedStyles } from '@/components/shared/sharedStyles';
import { ASImage } from '@/components';

type Props = React.ComponentProps<typeof ASImage> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASImage.
 *
 * Applies the structural props that are constant across every ASImage
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASImage directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppImage: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASImage
    roundImageSize={0}
    resizeMethod={'auto'}
    resizeMode={'contain'}
    hardCodeStyle={
      sharedStyles.dataClasificationOpenAccountImageAtmCardsImageHardCode
    }
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppImage;
