import React from 'react';
import { StyleProp } from 'react-native';
import { color } from '@/assets';
import { sharedStyles } from '@/components/shared/sharedStyles';
import { ASIconButton } from '@/components';

type Props = React.ComponentProps<typeof ASIconButton> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASIconButton.
 *
 * Applies the structural props that are constant across every ASIconButton
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASIconButton directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppIconButton: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASIconButton
    iconColor={color.brand.primary}
    size={32.00161254010163}
    containerStyle={sharedStyles.homeIconIconButtonAsiconButtonIconContainer}
    iconStyles={sharedStyles.homeIconIconButtonAsiconButtonIconIconStyles}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppIconButton;
