import React from 'react';
import { StyleProp } from 'react-native';
import { color, text } from '@/assets';
import { sharedStyles } from '@/components/shared/sharedStyles';
import { ASProgressBar } from '@/components';

type Props = React.ComponentProps<typeof ASProgressBar> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASProgressBar.
 *
 * Applies the structural props that are constant across every ASProgressBar
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASProgressBar directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppProgressBar: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASProgressBar
    activeColor={color.brand.primary}
    inActiveColor={color.surface.background}
    progressValue={20}
    progressBarTitle={''}
    progressCurrentStyle={
      sharedStyles.identityIdcardPhotoContainerProgressBarAsprogrProgressBarProgressCurrent
    }
    progressBarStyle={
      sharedStyles.identityIdcardPhotoContainerProgressBarAsprogrProgressBarProgressBar
    }
    progressTitleStyle={[
      text.label.medium,
      sharedStyles.identityIdcardPhotoContainerProgressBarAsprogrProgressBarProgressTitle,
    ]}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppProgressBar;
