import React from 'react';
import { StyleProp } from 'react-native';
import { ASRow } from '@/components';

type Props = React.ComponentProps<typeof ASRow> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASRow.
 *
 * Applies the structural props that are constant across every ASRow
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASRow directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppRow: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASRow
    backgroundImageResizeMode={'contain'}
    scrollable={false}
    scrollDirection={'horizontal'}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppRow;
