import React from 'react';
import { StyleProp } from 'react-native';
import { color, space } from '@/assets';
import { ASRadioButton } from '@/components';

type Props = React.ComponentProps<typeof ASRadioButton> & {
  widgetId?: string;
  style?: StyleProp<any>;
  children?: React.ReactNode;
};

/**
 * Auto-generated thin wrapper around ASRadioButton.
 *
 * Applies the structural props that are constant across every ASRadioButton
 * instance as overridable defaults, so call sites only declare what varies. This
 * removes the repeated prop blocks SonarQube reports as duplicated code. The
 * rendered element is identical to using ASRadioButton directly.
 * Generated by the widget-wrapper hoisting pass — do not edit by hand.
 */
const AppRadioButton: React.FC<Props> = ({ widgetId, ...rest }) => (
  <ASRadioButton
    activeColor={'#c4c4c4'}
    inActiveColor={color.border.default}
    axis={'horizontal'}
    buttonPosition={'left'}
    spacing={space['2']}
    radioType={'default'}
    name={widgetId}
    testId={widgetId}
    {...rest}
  />
);

export default AppRadioButton;
